/**
 * Clean the database
 * Deletes all nodes and relationships
 * Generated by RagForge
 */

import { createRagClient } from '../client.js';
import readline from 'readline/promises';
import { stdin as input, stdout as output } from 'process';

const rag = createRagClient();

async function main() {
  console.log('⚠️  WARNING: This will delete ALL data in the database!\n');

  const rl = readline.createInterface({ input, output });
  const answer = await rl.question('Are you sure you want to continue? (yes/no): ');
  rl.close();

  if (answer.toLowerCase() !== 'yes') {
    console.log('Operation cancelled.');
    await rag.close();
    return;
  }

  console.log('\n🗑️  Deleting all nodes and relationships...');

  try {
    await rag.client.run('MATCH (n) DETACH DELETE n');
    console.log('✅ Database cleaned successfully!');
  } catch (error) {
    console.error('❌ Failed to clean database:', error);
    process.exit(1);
  } finally {
    await rag.close();
  }
}

main();
