/**
 * Ingest code from configured source paths
 * Generated by RagForge
 *
 * This script reads the source configuration from ragforge.config.yaml
 * to ensure correct path resolution regardless of where it's run from.
 */

import { IncrementalIngestionManager } from '@luciformresearch/ragforge-runtime';
import { createRagClient } from '../client.js';
import { loadConfig } from '../load-config.js';

const rag = createRagClient();

console.log('🔄 Starting code ingestion...\n');

const manager = new IncrementalIngestionManager(rag.client);

// Load source configuration from ragforge.config.yaml
// This ensures correct path resolution when running from generated/ directory
const fullConfig = await loadConfig();
const sourceConfig = fullConfig.source;

if (!sourceConfig) {
  throw new Error('No source configuration found in ragforge.config.yaml');
}

console.log('📋 Source configuration loaded from config:');
console.log(`   Type: ${sourceConfig.type}`);
console.log(`   Adapter: ${sourceConfig.adapter}`);
console.log(`   Root: ${sourceConfig.root}`);
console.log('');

try {
  // Parse and ingest (incremental by default)
  const stats = await manager.ingestFromPaths(sourceConfig, {
    incremental: true,
    verbose: true
  });

  console.log('\n✅ Ingestion complete!');
  console.log(`   Created: ${stats.created}`);
  console.log(`   Updated: ${stats.updated}`);
  console.log(`   Unchanged: ${stats.unchanged}`);
  console.log(`   Deleted: ${stats.deleted}`);

} catch (error) {
  console.error('❌ Ingestion failed:', error);
  process.exit(1);
} finally {
  await rag.close();
}
