/**
 * Complete setup script
 * Runs: ingestion → indexes → embeddings → summaries
 * Generated by RagForge
 */

import { spawn } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

async function runCommand(command: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(command, args, {
      cwd: projectRoot,
      stdio: 'inherit',
      shell: true
    });

    proc.on('exit', code => {
      if (code === 0) resolve();
      else reject(new Error(`Command failed with code ${code}`));
    });
  });
}

async function main() {
  console.log('🚀 RagForge Setup - Complete Initialization\n');
  console.log('='.repeat(60));

  // Step 1: Ingest code
  console.log('\n📥 Step 1/3: Ingesting code...\n');
  await runCommand('npm', ['run', 'ingest']);

  // Step 2: Create vector indexes
  console.log('\n📊 Step 2/3: Creating vector indexes...\n');
  await runCommand('npm', ['run', 'embeddings:index']);

  // Step 3: Generate embeddings
  console.log('\n🔢 Step 3/3: Generating embeddings...\n');
  await runCommand('npm', ['run', 'embeddings:generate']);


  console.log('\n' + '='.repeat(60));
  console.log('✅ Setup complete! Your RAG system is ready.\n');
}

main().catch(error => {
  console.error('❌ Setup failed:', error);
  process.exit(1);
});
