/**
 * Watch source files and automatically ingest changes
 * Uses batching to efficiently handle multiple file changes
 * Generated by RagForge
 */

import { IncrementalIngestionManager, FileWatcher } from '@luciformresearch/ragforge-runtime';
import { createRagClient } from '../client.js';
import { spawn } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

const rag = createRagClient();
const manager = new IncrementalIngestionManager(rag.client);

// Source configuration (from ragforge.config.yaml)
const sourceConfig = {
  type: 'code' as const,
  root: path.resolve(projectRoot, '..', '/home/luciedefraiteur/LR_CodeRag/ragforge/packages'),
  include: ["**/src/**/*.ts","**/lib/**/*.ts"],
  exclude: ["**/node_modules/**","**/dist/**","**/*.test.ts","**/*.spec.ts"],
  adapter: 'typescript' as const
};

// Watch configuration
const watchConfig = {
  batchInterval: 1000,
  verbose: true,
  onBatchStart: (fileCount: number) => {
    console.log(`\n🔄 Processing batch of ${fileCount} file(s)...`);
  },
  onBatchComplete: (stats) => {
    console.log(`✅ Batch complete: ${stats.created + stats.updated} scope(s) updated`);
    
    // Auto-generate embeddings for dirty scopes only
    if (stats.created + stats.updated > 0) {
      console.log('🔢 Generating embeddings for modified scopes...');
      spawn('npm', ['run', 'embeddings:generate', '--', '--only-dirty'], {
        cwd: projectRoot,
        stdio: 'inherit',
        shell: true
      });
    }
    
  },
  onBatchError: (error) => {
    console.error('❌ Batch failed:', error);
  }
};

console.log('👀 Starting file watcher...\n');
console.log('   Watching patterns:');
console.log('     - **/src/**/*.ts');
console.log('     - **/lib/**/*.ts');
console.log('\n   Ignoring patterns:');
console.log('     - **/node_modules/**');
console.log('     - **/dist/**');
console.log('     - **/*.test.ts');
console.log('     - **/*.spec.ts');
console.log(`\n   Batch interval: 1000ms`);
console.log('   Press Ctrl+C to stop\n');

const watcher = new FileWatcher(manager, sourceConfig, watchConfig);

try {
  await watcher.start();

  // Handle graceful shutdown
  process.on('SIGINT', async () => {
    console.log('\n\n🛑 Stopping watcher...');
    await watcher.stop();
    await rag.close();
    process.exit(0);
  });

  // Keep process alive
  await new Promise(() => {});
} catch (error) {
  console.error('❌ Watcher failed:', error);
  await rag.close();
  process.exit(1);
}
