import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = __dirname;
const YAML_PATH = path.resolve(PROJECT_ROOT, 'ragforge.config.yaml');

function ensureConfigExists(): void {
  try {
    fs.accessSync(YAML_PATH, fs.constants.R_OK);
  } catch {
    throw new Error(
      `Cannot find ragforge.config.yaml next to generated artifacts.\n` +
      `Expected at: ${YAML_PATH}\n` +
      `Make sure you keep the config generated by RagForge alongside your generated code.`
    );
  }
}

function substituteEnvVars(obj: any): any {
  if (typeof obj === 'string') {
    // Replace ${VAR} or $VAR with process.env.VAR
    return obj.replace(/\$\{([^}]+)\}|\$([A-Z_][A-Z0-9_]*)/g, (_, braced, unbraced) => {
      const varName = braced || unbraced;
      return process.env[varName] || '';
    });
  }
  if (Array.isArray(obj)) {
    return obj.map(substituteEnvVars);
  }
  if (obj && typeof obj === 'object') {
    const result: any = {};
    for (const key of Object.keys(obj)) {
      result[key] = substituteEnvVars(obj[key]);
    }
    return result;
  }
  return obj;
}

export function loadConfig(): any {
  ensureConfigExists();
  const yamlContent = fs.readFileSync(YAML_PATH, 'utf-8');
  const config = yaml.load(yamlContent) as any ?? {};
  return substituteEnvVars(config);
}

export const config = loadConfig();
