#!/usr/bin/env npx tsx
/**
 * Test script for file tools
 *
 * Usage:
 *   npx tsx test-file-tools.ts [project-root]
 *
 * This tests:
 *   - read_file: Read a file with line numbers
 *   - write_file: Create a new file
 *   - edit_file: Modify an existing file
 */

import { generateFileTools } from '@luciformresearch/ragforge-core';
import * as path from 'path';
import * as fs from 'fs';

const projectRoot = process.argv[2] || process.cwd();

console.log('🧪 Testing File Tools');
console.log('═'.repeat(50));
console.log(`   Project root: ${projectRoot}`);
console.log('');

// Create file tools context
const ctx = {
  projectRoot,
  onFileModified: async (filePath: string, changeType: string) => {
    console.log(`   📣 onFileModified: ${changeType} - ${filePath}`);
  }
};

const { handlers } = generateFileTools(ctx);

async function runTests() {
  // Test 1: Read an existing file
  console.log('📖 Test 1: read_file');
  console.log('-'.repeat(40));

  try {
    // Try to read package.json or any existing file
    const readResult = await handlers.read_file({
      path: 'package.json',
      limit: 20
    });

    if (readResult.error) {
      console.log(`   ❌ Error: ${readResult.error}`);
    } else {
      console.log(`   ✅ Read ${readResult.lines_read} lines from ${readResult.path}`);
      console.log(`   Total lines: ${readResult.total_lines}`);
      console.log('   Preview:');
      const preview = readResult.content.split('\n').slice(0, 5).join('\n');
      console.log(preview.split('\n').map((l: string) => `      ${l}`).join('\n'));
    }
  } catch (err: any) {
    console.log(`   ❌ Exception: ${err.message}`);
  }

  console.log('');

  // Test 2: Write a new file
  console.log('✏️  Test 2: write_file');
  console.log('-'.repeat(40));

  const testFilePath = 'test-output.txt';
  const testContent = `// Generated by file-tools test
// Date: ${new Date().toISOString()}

export const greeting = "Hello from file tools!";

export function add(a: number, b: number): number {
  return a + b;
}
`;

  try {
    const writeResult = await handlers.write_file({
      path: testFilePath,
      content: testContent
    });

    console.log(`   ✅ Created ${writeResult.path}`);
    console.log(`   Change type: ${writeResult.change_type}`);
    console.log(`   Lines written: ${writeResult.lines_written}`);
    console.log(`   Hash: ${writeResult.hash}`);
  } catch (err: any) {
    console.log(`   ❌ Exception: ${err.message}`);
  }

  console.log('');

  // Test 3: Edit the file we just created
  console.log('🔧 Test 3: edit_file');
  console.log('-'.repeat(40));

  try {
    const editResult = await handlers.edit_file({
      path: testFilePath,
      old_string: 'return a + b;',
      new_string: 'const result = a + b;\n  console.log(`Adding ${a} + ${b} = ${result}`);\n  return result;'
    });

    console.log(`   ✅ Edited ${editResult.path}`);
    console.log(`   Diff:`);
    const diffLines = editResult.diff.split('\n').slice(0, 15);
    console.log(diffLines.map((l: string) => `      ${l}`).join('\n'));
  } catch (err: any) {
    console.log(`   ❌ Exception: ${err.message}`);
  }

  console.log('');

  // Test 4: Read the edited file
  console.log('📖 Test 4: read_file (after edit)');
  console.log('-'.repeat(40));

  try {
    const readResult = await handlers.read_file({ path: testFilePath });

    console.log(`   ✅ Read ${readResult.lines_read} lines`);
    console.log('   Content:');
    console.log(readResult.content.split('\n').map((l: string) => `      ${l}`).join('\n'));
  } catch (err: any) {
    console.log(`   ❌ Exception: ${err.message}`);
  }

  console.log('');

  // Test 5: Fuzzy matching test
  console.log('🔍 Test 5: edit_file with fuzzy matching');
  console.log('-'.repeat(40));

  // Create a file with some indentation
  const fuzzyTestFile = 'test-fuzzy.ts';
  const fuzzyContent = `export class Calculator {
  add(a: number, b: number): number {
    return a + b;
  }

  subtract(a: number, b: number): number {
    return a - b;
  }
}
`;

  await handlers.write_file({ path: fuzzyTestFile, content: fuzzyContent });

  try {
    // Try to edit with slightly different indentation (should still match)
    const editResult = await handlers.edit_file({
      path: fuzzyTestFile,
      old_string: `subtract(a: number, b: number): number {
  return a - b;
}`,  // Note: different indentation than original
      new_string: `subtract(a: number, b: number): number {
    const result = a - b;
    return result;
  }`
    });

    console.log(`   ✅ Fuzzy match succeeded!`);
    console.log(`   Diff:`);
    const diffLines = editResult.diff.split('\n').slice(0, 10);
    console.log(diffLines.map((l: string) => `      ${l}`).join('\n'));
  } catch (err: any) {
    console.log(`   ❌ Fuzzy match failed: ${err.message}`);
  }

  console.log('');

  // Cleanup
  console.log('🧹 Cleanup');
  console.log('-'.repeat(40));

  try {
    fs.unlinkSync(path.join(projectRoot, testFilePath));
    fs.unlinkSync(path.join(projectRoot, fuzzyTestFile));
    console.log(`   ✅ Removed test files`);
  } catch (err) {
    console.log(`   ⚠️  Could not clean up test files`);
  }

  console.log('');
  console.log('═'.repeat(50));
  console.log('✅ File tools tests complete!');
}

runTests().catch(console.error);
